### ISSUE TITLE
editor() errors ghosting

### ISSUE THREAD

**Issue by Blain20** [dworkin/dgd#19] opened 2019-10-02 05:09 UTC
When editor() is called, the driver is called with path_read().  Any errors that occur after editor() is called do not show up in call_trace() when driver->runtime_error() is called.  So, whichever function calls editor() is that second-to-last entry in the call trace, and then runtime_error is the last.  I suppose this may be intentional, but I just wanted to bring it up just in case it wasn't.

**Comment by dworkin** [comment] 2019-10-02 12:15
I can't reproduce this.

This is probably an artefact of the way your mudlib handles errors.

**Comment by Blain20** [comment] 2019-10-03 02:29
I reproduced this on a bare bones test lib before making the report.  I first noticed it a few years ago, but though it was related to atomic functions in the kernel lib.  I no longer use a kernel lib in my usual setup, so I investigated.

My bare bones test lib consists of an empty auto.c and std.h, so the only relevant code is in driver.c and editor.c.  I throw an error in editor->path_read().  In driver->runtime_error(), the call trace is missing the call to driver->path_read() and the call to editor->path_read().  It seems you have DGD treating the call to driver->path_read() as though atomic, perhaps?  I only bring it up in case that's not your intention, so this may be a feature and not a bug.  It just makes it a little more difficult to pinpoint where the error occurs.

*** /driver.c ***
void initialize()
{
  object obj;

  send_message("Driver Loaded\n");
  obj = compile_object("/editor");
  obj->start();
}

string path_read(string path)
{
  object obj;

  obj = previous_object();
  send_message("path_read: "+object_name(obj)+"\n");
  return obj->path_read(path);
}

*** /editor.c
void start()
{
  "/driver"->console("starting editor\n");
  editor("e /tmp.c");
}

string path_read(string path)
{
  "/driver"->console("ed:path_read:"+path+"\n");
  error("foo");
  return path;
}

string runtime_error(string error, int caught, int ticks)
{
  int idx, max;
  mixed **trace;
  string *out;

  send_message("[Runtime] "+error+"\n");
  trace = call_trace();
  max = sizeof(trace);
  out = allocate(max);
  for(idx = 0; idx < max; idx++)
  {
    out[idx] = trace[idx][TRACE_LINE] + "\t"
      + trace[idx][TRACE_PROGNAME] + "\t"
      + trace[idx][TRACE_OBJNAME] + "\t"
      + trace[idx][TRACE_FUNCTION];
  }
  send_message(implode(out, "\n")+"\n");
}

*** console
$ ./start
Driver Loaded
starting editor
path_read: /editor#3
ed:path_read:/tmp.c
[Runtime] foo
26      /driver /driver initialize
6       /editor /editor       start
235     /driver /driver runtime_error
foo
Config error: initialization failed

*** end

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dworkin** [comment] 2019-10-03 09:23
Interesting. I had the situation exactly reversed; rather than you seeing artefacts of error processing, my own library was preventing me from analysing this properly.

**Comment by dworkin** [comment] 2019-10-03 11:57
Should be fixed by https://github.com/dworkin/dgd/commit/47fd668cbf540aaa1316a0172cb8405d5fd257de.

**Comment by Blain20** [comment] 2019-10-03 18:10
Thank you.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Closed** 2019-10-03 21:05 UTC
Labels: bug, feedback
